"""one-down migration

Revision ID: acaf5b7c5f33
Revises: 
Create Date: 2021-06-29 22:41:18.822785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acaf5b7c5f33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_column('todo', 'data_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('data_created', sa.DATETIME(), nullable=True))
    op.drop_column('todo', 'date_created')
    # ### end Alembic commands ###
